spring.application.name=ELEC5619_Practical03_Group_7

spring.datasource.url=jdbc:mysql://localhost:3306/OnlineBookstore
spring.datasource.username=root
spring.datasource.password=lizhihui666
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver